### ISSUE TITLE
dish model

### ISSUE THREAD

**Issue by gabzn** [smart-bills/smart_bills#30]
Will be created only when the host clicks on split by dishes.
#15 will (maybe) change the attributes here
- [ ] Dish Name
- [ ] Dish Amount
- [ ] Paid (boolean)   
- [ ] User Email
- [ ] Description  (Inherited from Bill)
- [ ] Date             (Inherited from Bill)
- [ ] Bill ID           (Inherited from Bill)
- [ ] Store Name (Inherited from Bill)

**Comment by channnx** [comment]
this maybe hold on till how the google vision API works, and to see if it's doable, otherwise we need to think another way to store the dish
